title: KNOCref\S.O.P's | XDIA REALISM MILSIM
description: This is the page for information regarding our S.O.P's\General Information under the UNCLASSIFIED Clearance & Etc.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
